### ISSUE TITLE
Sql error after clicking 'Save Promotion'

### ISSUE THREAD

**Issue by ghost** [SvePu/User-Activity-Promotion#3]
`MyBB has experienced an internal SQL error and cannot continue.

**SQL Error:**
1054 - Unknown column 'thankyoulike' in 'field list'
**Query:**
UPDATE mybb_promotions SET `thankyoulike`=0, `thankyouliketype`='>' WHERE pid='3'`

**Comment by SvePu** [comment]
Please reinstall the plugin:
https://youtu.be/8ZyVznFTxX8

**Comment by SvePu** [comment]
Sorry....I cab't confirm that....try the newest release please!
